- name: Set up corstat server 
  hosts: all
  become: yes

  vars:
    ports_conf_src: "ports.conf"
    reverse_proxy_conf_src: "reverse-proxy.conf"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Copy ports.conf to /etc/apache2/ports.conf
      copy:
        src: "{{ ports_conf_src }}"
        dest: /etc/apache2/ports.conf
        owner: root
        group: root
        mode: '0644'

    - name: Restart Apache
      service:
        name: apache2
        state: restarted

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Copy reverse-proxy.conf to /etc/nginx/sites-available/reverse-proxy.conf
      copy:
        src: "{{ reverse_proxy_conf_src }}"
        dest: /etc/nginx/sites-available/reverse-proxy.conf
        owner: root
        group: root
        mode: '0644'

    - name: Create symbolic link for reverse-proxy.conf
      file:
        src: /etc/nginx/sites-available/reverse-proxy.conf
        dest: /etc/nginx/sites-enabled/reverse-proxy.conf
        state: link

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Install Docker dependencies
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt cache (for Docker)
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Upgrade Docker CE
      apt:
        name: docker-ce
        state: latest

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Download Docker Compose
      shell: |
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

    - name: Make Docker Compose binary executable
      file:
        path: /usr/local/bin/docker-compose
        mode: '0755'
        owner: root
        group: root
        state: file

    - name: Create a symlink to docker-compose in /usr/bin
      file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link
        force: yes

    - name: Copy multiple files to remote host
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - { src: '../Docker/docker-compose.yml', dest: '/home/ubuntu/docker-compose.yml' }
        - { src: '../Docker/Dockerfile', dest: '/home/ubuntu/Dockerfile' }
        - { src: '../Docker/sonar.properties', dest: '/home/ubuntu/sonar.properties' }

    - name: Run Docker Compose
      command: docker-compose up -d
      args:
        chdir: /home/ubuntu
